version: "3.7"

services:
  db:
    image: mysql:8.0.32-debian
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    volumes:
      - /var/lib/adminer
    depends_on:
      - db
